#*************************************************************#
#
#   Ensemble, 2_00
#   Copyright 2004 Cornell University, Hebrew University
#           IBM Israel Science and Technology
#   All rights reserved.
#
#   See ensemble/doc/license.txt for further information.
#
#*************************************************************#
ENSROOT = ../../..
include $(ENSROOT)/mk/config.mk
include $(ENSROOT)/mk/rules.mk

all:
	javac *.java

clean: 
	$(RM) *.class

#doc : 
#	mkdir -p docs
#	javadoc ensemble/hot/*.java -d docs
