#*************************************************************#
#
#   Ensemble, 1.10
#   Copyright 2001 Cornell University, Hebrew University
#   All rights reserved.
#
#   See ensemble\doc\license.txt for further information.
#
#*************************************************************#
#*************************************************************#
ENSROOT = ..
!include $(ENSROOT)\mk\config.nmk

#*************************************************************#
all: main_all install socket
	cd ..\demo $(SUBMAKE) socketopt
#*************************************************************#

!include $(ENSROOT)\mk\preamble.nmk
!include $(ENSROOT)\mk\ocamlopt.nmk
!include $(ENSROOT)\mk\files.nmk
!include $(ENSROOT)\mk\main.nmk
!include $(ENSROOT)\mk\tools.nmk
!include $(ENSROOT)\mk\install.nmk
!include $(DEPEND)
#*************************************************************#

fast: $(OBJD)\_ssocket$(CMO)
	cp $(OBJD)\_ssocket$(CMO) $(OBJD)\socket.cmx
	-$(RM) $(OBJD)\hsys$(CMO)
