#*************************************************************#
#
#   Ensemble, (Version 1.00)
#   Copyright 2000 Cornell University
#   All rights reserved.
#
#   See ensemble/doc/license.txt for further information.
#
#*************************************************************#
#*************************************************************#
ENSROOT = ..
DIR = opt
#*************************************************************#
all: main_all install socket
	cd ..\demo $(SUBMAKE) socketopt
#*************************************************************#
!include $(ENSROOT)\mk\config.nmk
!include $(ENSROOT)\mk\preamble.nmk
!include $(ENSROOT)\mk\ocamlopt.nmk
!include $(ENSROOT)\mk\files.nmk
!include $(ENSROOT)\mk\main.nmk
!include $(ENSROOT)\mk\tools.nmk
!include $(ENSROOT)\mk\install.nmk
!include $(DEPEND)
#*************************************************************#

fast: $(OBJD)\_ssocket$(CMO)
	cp $(OBJD)\_ssocket$(CMO) $(OBJD)\socket.cmx
	-$(RM) $(OBJD)\hsys$(CMO)
