#*************************************************************#
ENSROOT = ..
!include ..\mk\config.nmk
#*************************************************************#

all: hevea ce.html ref.pdf tut.pdf ejava_doc cejava_doc #projects.ps

TUT_SRC =\
	tut.tex\
	install.tex\
	config.tex\
	def.tex\
	demo.tex\
	appl_ml.tex\
	appl_c.tex\
	appl_text.tex\
	exec_tut.tex\
	property.tex\
	pgp.tex\
	view_state.tex


REF_SRC =\
	layers\*.tex\
	ref.tex\
	id.tex\
	def.tex\
	event.tex\
	event_prot.tex\
	layer_antmy.tex\
	layer_model.tex\
	layer_hdlrs.tex\
	layer_ref.tex\
	vsync.tex\
	exec_ref.tex\
	membership.tex\
	bimodal.tex\
	security.tex\
	unsafe.tex

ref.pdf : $(REF_SRC)
	pdflatex ref
	pdflatex ref
	pdflatex ref

ref_hack : 
	pdflatex ref

tut.pdf : $(TUT_SRC)
	pdflatex tut
	pdflatex tut
	pdflatex tut

#projects.dvi: projects.tex
#	latex projects
#	latex projects
#	dvips projects.dvi -o projects.ps 

clean:
	$(RM) *.dvi *~ *.log *.aux *.toc *.lof *.lot 
	$(RM) TAGS layers\*.aux .nfs* *~ .*~ *.haux *.image.tex .#?* *.gif
	$(RMDIR) ce\html
	cd layers& $(MAKE) clean
	$(RMDIR) tut ref 
	$(RM) ref.html tut.html 

realclean: clean
	$(RM) *.pdf

force: clean all

tags:
	etags *.tex ..\layers\*\*.tex

hevea: setup tut.html ref.html cleanup

setup : 
	$(RM) def.tex
	ln def-hevea.tex def.tex

cleanup : 
	$(RM) def.tex
	ln def-reg.tex def.tex

tut.html : 
	hevea -fix tut.tex
	$(RMDIR) tut
	$(MKDIR) tut
	$(MV) tut.html tut
	cd tut& hacha tut.html

ref.html : 
	hevea -fix ref.tex
	imagen ref
	$(RMDIR) ref
	$(MKDIR) ref
	$(MV) ref.html *.gif ref\
	cd ref&	hacha ref.html

ce.html : 
	cd ce& doxygen ce-config.doxygen

ejava_doc : 
	$(RMDIR) ejava
	$(RMDIR) docs
	cd ..\ejava& $(MAKE) doc
	$(MV) ..\ejava\docs .
	$(MV) docs ejava

cejava_doc : 
	$(RMDIR) cejava
	$(RMDIR) docs
	cd ..\cejava& $(MAKE) doc
	$(MV) ..\cejava\docs .
	$(MV) docs cejava

VERSION = 1_40

build : 
	cd ..& tar -cf doc-$(VERSION).tar doc\{*.pdf,tut,ref,ce\html,maestro,ejava}& gzip -f doc-$(VERSION).tar& mv doc-$(VERSION).tar.gz ..
