/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ensemble_Group */

#ifndef _Included_ensemble_Group
#define _Included_ensemble_Group
#ifdef __cplusplus
extern "C" {
#endif
#undef ensemble_Group_PRE
#define ensemble_Group_PRE 0L
#undef ensemble_Group_JOINING
#define ensemble_Group_JOINING 1L
#undef ensemble_Group_NORMAL
#define ensemble_Group_NORMAL 2L
#undef ensemble_Group_BLOCKED
#define ensemble_Group_BLOCKED 3L
#undef ensemble_Group_LEAVING
#define ensemble_Group_LEAVING 4L
#undef ensemble_Group_LEFT
#define ensemble_Group_LEFT 5L
/*
 * Class:     ensemble_Group
 * Method:    natInit
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ensemble_Group_natInit
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     ensemble_Group
 * Method:    natJoin
 * Signature: (Lensemble/JoinOps;)J
 */
JNIEXPORT jlong JNICALL Java_ensemble_Group_natJoin
  (JNIEnv *, jobject, jobject);

/*
 * Class:     ensemble_Group
 * Method:    natLeave
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ensemble_Group_natLeave
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ensemble_Group
 * Method:    natCast
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_ensemble_Group_natCast
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     ensemble_Group
 * Method:    natSend
 * Signature: (J[I[B)V
 */
JNIEXPORT void JNICALL Java_ensemble_Group_natSend
  (JNIEnv *, jobject, jlong, jintArray, jbyteArray);

/*
 * Class:     ensemble_Group
 * Method:    natSend1
 * Signature: (JI[B)V
 */
JNIEXPORT void JNICALL Java_ensemble_Group_natSend1
  (JNIEnv *, jobject, jlong, jint, jbyteArray);

/*
 * Class:     ensemble_Group
 * Method:    natPrompt
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ensemble_Group_natPrompt
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ensemble_Group
 * Method:    natSuspect
 * Signature: (J[I)V
 */
JNIEXPORT void JNICALL Java_ensemble_Group_natSuspect
  (JNIEnv *, jobject, jlong, jintArray);

/*
 * Class:     ensemble_Group
 * Method:    natXferDone
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ensemble_Group_natXferDone
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ensemble_Group
 * Method:    natRekey
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ensemble_Group_natRekey
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ensemble_Group
 * Method:    natChangeProtocol
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ensemble_Group_natChangeProtocol
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     ensemble_Group
 * Method:    natChangeProperties
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ensemble_Group_natChangeProperties
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
