#*************************************************************#
#
# DEMO directory default Makefile
#
# This makefile includes ocaml.mk definitions for building bytecode
# executables.  Makefile.opt.nt is the same file, but includes
# ocamlopt.mk.
#
# Author: Mark Hayden, 8\96
#
#*************************************************************#
ENSROOT = ..
!include $(ENSROOT)\mk\preamble.nmk
!include $(ENSROOT)\mk\config.nmk
!include $(ENSROOT)\mk\ocaml.nmk
!include Makefile.base.nt

# Build using the optimizing compiler
opt:
	$(MAKE) -f Makefile.opt.nt
crypto-opt : 
	$(MAKE) -f Makefile.opt.nt crypto
socketopt:
	$(MAKE) -f Makefile.opt.nt socket
just_ensemble:
	$(MAKE) -f Makefile.opt.nt just_ensemble

