#*************************************************************#
#
#   Ensemble, (Version 0.70p1)
#   Copyright 2000 Cornell University
#   All rights reserved.
#
#   See ensemble/doc/license.txt for further information.
#
#*************************************************************#
#*************************************************************#
#
# DEMO directory Makefile
#
# Author: Mark Hayden, 8/96
#
#*************************************************************#
ENSROOT = ..
include $(ENSROOT)/mk/preamble.mk
include $(ENSROOT)/mk/config.mk
include $(ENSROOT)/mk/ocamlopt.mk
include Makefile.base

just_ensemble: lensemble$(CMO) $(ENSCONFDEP_skt)
	$(MLLINK) -o ensemble$(EXE) $(LIBSYS) $(ENSCONF_skt) lensemble$(CMO)
	strip ensemble$(EXE)
	ls -l ensemble$(EXE)
