#*************************************************************#
#
#   Ensemble, (Version 1.00)
#   Copyright 2000 Cornell University
#   All rights reserved.
#
#   See ensemble/doc/license.txt for further information.
#
#*************************************************************#
all:
	cd .. ; make

clean:
	rm -f *.dvi *~ *.log *.aux *.toc *.lof *.lot TAGS
