#*************************************************************#
#
#   Ensemble, 1.10
#   Copyright 2001 Cornell University, Hebrew University
#   All rights reserved.
#
#   See ensemble/doc/license.txt for further information.
#
#*************************************************************#
ENSLIB = ..\..\lib\nt
LIBHOT = libhot-nt.lib
LIBMAE = libmae-nt.lib
CC = cl /nologo
LIBCRYPTO =
#LIBCRYPTO = $(ENSLIB)\libcryptoc-nt.lib
MAESTRO_OBJ = 	Maestro_Types.obj \
		Maestro_GroupMember.obj \
		Maestro_ClSv.obj \
		Maestro_CSX.obj \
		Maestro_Prim.obj \
		Maestro_Group.obj


CFLAGS = /TP /I$(ENSLIB) 
LDFLAGS = /link $(LIBMAE) $(LIBCRYPTO) /NODEFAULTLIB \
	libcmt.lib libcpmt.lib libcimt.lib \
	oldnames.lib kernel32.lib wsock32.lib

all: maestro_test.exe maestro_perf.exe group.exe

$(LIBMAE): $(ENSLIB)\$(LIBHOT) $(MAESTRO_OBJ)
	lib /out:$(LIBMAE) $(ENSLIB)\$(LIBHOT) $(MAESTRO_OBJ)

maestro_test.exe: $(LIBMAE) maestro_test.c
	cl $(CFLAGS) maestro_test.c $(LDFLAGS)

maestro_perf.exe: $(LIBMAE) maestro_perf.c
	cl $(CFLAGS) maestro_perf.c $(LDFLAGS)

group.exe: $(LIBMAE) group.c
	cl $(CFLAGS) group.c $(LDFLAGS)

clean:
	-del /Q *.obj
	-del /Q *.exe
	-del /Q libmae-nt.lib

depend: 
	@echo "Maestro: (make depend): currently not implemented on WIN32"
