ENSROOT = ..
!include $(ENSROOT)\mk\config.nmk

.SUFFIXES: .java .class
.java.class:
	javac $<

all: EnsDemoOutboard.class
	$(CP) $(ENSROOT)\bin\nt\outboard$(EXE) .
	javac ensemble\hot\*.java
	chmod +x EnsDemoOutboard.class

clean:
	-del /Q ensemble\hot\*.class
	-del /Q *.class
