#*************************************************************#
# MAKEFILE: tools Makefile
#*************************************************************#
ENSROOT = ..
!include $(ENSROOT)\mk\preamble.nmk
!include $(ENSROOT)\mk\config.nmk
#*************************************************************#

all :\
	$(ENSBIN)\$(EMRG)

$(ENSBIN)\$(EMRG): 
	ocamlc -c emrg.ml 
	ocamlc -o $(ENSBIN)\$(EMRG) emrg.cmo

clean : 
	$(RM) *.cm*

realclean : clean
#*************************************************************#