#*************************************************************#
#
#   Ensemble, 1.10
#   Copyright 2001 Cornell University, Hebrew University
#   All rights reserved.
#
#   See ensemble\doc\license.txt for further information.
#
#*************************************************************#
#*************************************************************#
# MAKEFILE: tools Makefile
#*************************************************************#
ENSROOT = ..
!include $(ENSROOT)\mk\config.nmk
!include $(ENSROOT)\mk\sub.nmk
#*************************************************************#
