#*************************************************************#
#
#   Ensemble, (Version 1.00)
#   Copyright 2000 Cornell University
#   All rights reserved.
#
#   See ensemble/doc/license.txt for further information.
#
#*************************************************************#
#*************************************************************#
ENSROOT = ..
DIR = def
#*************************************************************#
all: main_all install
	cd ..\demo $(SUBMAKE)
#*************************************************************#
!include $(ENSROOT)\mk\config.nmk
!include $(ENSROOT)\mk\preamble.nmk
!include $(ENSROOT)\mk\ocaml.nmk
!include $(ENSROOT)\mk\files.nmk
!include $(ENSROOT)\mk\main.nmk
!include $(ENSROOT)\mk\tools.nmk
!include $(ENSROOT)\mk\install.nmk
!include $(ENSROOT)\mk\cross.nmk
!include $(ENSROOT)\mk\dynlink.nmk
!include $(DEPEND)
#*************************************************************#
