#*************************************************************#
#
#   Ensemble, 1.10
#   Copyright 2001 Cornell University, Hebrew University
#   All rights reserved.
#
#   See ensemble/doc/license.txt for further information.
#
#*************************************************************#
all:
	cd .. ; make

clean:
	rm -f *.dvi *~ *.log *.aux *.toc *.lof *.lot TAGS
