# Makefile for Maestro

MAKE            = nmake -f Makefile.nt
ROOT            = .
SRC             = maestro-nt


all:    
	(cd $(SRC)& $(MAKE))

clean:
	(cd $(SRC)& $(MAKE) clean)

realclean:	clean

depend:
	(cd $(SRC)& $(MAKE) depend)

