#*************************************************************#
#
# Main CS Makefile
#
# Author: Ohad Rodeh 8\2003
# Based on code by Mark Hayden
#
#*************************************************************#
ENSROOT = ..\..
!include $(ENSROOT)\mk\preamble.nmk
!include $(ENSROOT)\mk\config.nmk
#*************************************************************#

!if "$(PLATFORM)" == "nt"
clean : 
	$(RM_REC) *.dll
	$(RM_REC) *.pdb
	$(RM_REC) *.exe
!else
clean : 
	$(RM) ENS\*\*\*\*.dll
	$(RM) ENS\*\*\*\*.pdb
	$(RM) ENS\*\*\*\*.exe
!endif

#*************************************************************#
