#*************************************************************#
#
# Main CRYPTO Makefile
#
# Author: Ohad Rodeh 11\2001
# Based on code by Mark Hayden
#
#*************************************************************#
ENSROOT = ..\..

!include $(ENSROOT)\mk\config.nmk
!include $(ENSROOT)\mk\preamble.nmk

!ifdef OPT
!include $(ENSROOT)\mk\ocamlopt.nmk
!else
!include $(ENSROOT)\mk\ocaml.nmk
!endif
#*************************************************************#

all : fake\cryptokit_int.mli real\cryptokit_int.mli 
	cd fake& $(MAKE)
!ifdef CRYPTO
	cd real& $(MAKE)
!endif

fake\cryptokit_int.mli : cryptokit_int.mli
	$(CP) cryptokit_int.mli fake\

real\cryptokit_int.mli : cryptokit_int.mli
	$(CP) cryptokit_int.mli real\

clean : 
	$(RM) fake\cryptokit_int.mli real\cryptokit_int.mli 
	$(RM) *.cmi
	cd fake& $(MAKE) clean 
	cd real& $(MAKE) clean 

realclean : clean

#*************************************************************#


