#*************************************************************#
#
#   Ensemble, 1.10
#   Copyright 2001 Cornell University, Hebrew University
#   All rights reserved.
#
#   See ensemble\doc\license.txt for further information.
#
#*************************************************************#
#*************************************************************#
#
# LIFE: makefile for life demo
#
# Author: Mark Hayden, 8\96
#
#*************************************************************#
ENSROOT = ..\..
!include $(ENSROOT)\mk\preamble.nmk
!include $(ENSROOT)\mk\config.nmk
!include $(ENSROOT)\mk\ocaml.nmk
#*************************************************************#

.SUFFIXES: .ml .cmo .mli .cmi
.ml.cmo:
	ocamlc -c -I $(ENSLIB) $<
.mli.cmi:
	ocamlc -c -I $(ENSLIB) $<

#*************************************************************#

OBJS =\
        collector$(CMO)\
        lifetk$(CMO)\
	debug$(CMO)\
	rules$(CMO)\
	slave$(CMO)\
	master$(CMO)\
	life$(CMO)

#*************************************************************#

life: $(OBJS) $(ENSCONFDEP) $(ENSTK)
	ocamlc -custom -o life$(EXE) $(LIBTK) $(ENSCONF) $(ENSTK) $(OBJS)

#*************************************************************#

$(ENSTK):
	echo "lib\htk.cma library has not been compiled"

#*************************************************************#

clean:
	$(RM) *~ .*~ *.cm* .err TAGS core
	$(RM) life

depend:
	ocamldep -I $(ENSROOT)\lib *.ml* > $(DEPEND)

!include $(DEPEND)

#*************************************************************#
